# Generated by Django 5.0.6 on 2024-06-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userss',
            name='name',
            field=models.CharField(max_length=20, verbose_name=''),
        ),
    ]
