# Generated by Django 5.0.6 on 2024-06-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userss',
            name='address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userss',
            name='addresstolive',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userss',
            name='age',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userss',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userss',
            name='hobbies',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userss',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userss',
            name='specialty',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userss',
            name='surname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userss',
            name='university',
            field=models.TextField(max_length=50),
        ),
    ]
